/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @author FusionCharts Technologies LLP
 @version fusioncharts/3.2.4-release.8565

 @attributions (infers respective third-party copyrights)
 Highcharts JS v2.1.9 (modified) <http://www.highcharts.com/license>
 SWFObject v2.2 (modified) <http://code.google.com/p/swfobject/>
 JSON v2 <http://www.JSON.org/js.html>
 jQuery 1.7.1 <http://jquery.com/>
 Firebug Lite 1.3.0 <http://getfirebug.com/firebuglite>
*/
(function(){if(!window.FusionCharts||!window.FusionCharts.version){var a={},j=a.modules={},i=a.interpreters={},h=Object.prototype.toString,f=/msie/i.test(navigator.userAgent)&&!window.opera,b=!!document.createElementNS&&!!document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,e=function(a,d){var k,b;if(d instanceof Array)for(k=0;k<d.length;k+=1)typeof d[k]!=="object"?a[k]=d[k]:(typeof a[k]!=="object"&&(a[k]=d[k]instanceof Array?[]:{}),e(a[k],d[k]));else for(k in d)typeof d[k]===
"object"?(b=h.call(d[k]),b==="[object Object]"?(typeof a[k]!=="object"&&(a[k]={}),e(a[k],d[k])):b==="[object Array]"?(a[k]instanceof Array||(a[k]=[]),e(a[k],d[k])):a[k]=d[k]):a[k]=d[k];return a};a.extend=function(a,d,k,b){var g;if(k&&a.prototype)a=a.prototype;if(b===!0)e(a,d);else for(g in d)a[g]=d[g];return a};a.uniqueId=function(){return"chartobject-"+(a.uniqueId.lastId+=1)};a.uniqueId.lastId=0;a.policies={options:{swfSrcPath:["swfSrcPath",void 0],product:["product","v3"],insertMode:["insertMode",
"replace"],safeMode:["safeMode",!0],overlayButton:["overlayButton",void 0],containerBackgroundColor:["backgroundColor",void 0],chartType:["type",void 0]},attributes:{lang:["lang","EN"],"class":["className","FusionCharts"],id:["id",void 0]},width:["width","400"],height:["height","300"],src:["swfUrl",""]};i.stat=["swfUrl","id","width","height","debugMode","registerWithJS","backgroundColor","scaleMode","lang","detectFlashVersion","autoInstallRedirect"];a.parsePolicies=function(b,d,k){var f,g,e;for(g in d)if(a.policies[g]instanceof
Array)e=k[d[g][0]],b[g]=e===void 0?d[g][1]:e;else for(f in typeof b[g]!=="object"&&(b[g]={}),d[g])e=k[d[g][f][0]],b[g][f]=e===void 0?d[g][f][1]:e};a.parseCommands=function(a,d,k){var b,g;typeof d==="string"&&(d=i[d]||[]);b=0;for(g=d.length;b<g;b++)a[d[b]]=k[b];return a};a.core=function(c){if(!(this instanceof a.core)){if(arguments.length===1&&c instanceof Array&&c[0]==="private"){if(j[c[1]])return;j[c[1]]={};c[3]instanceof Array&&(a.core.version[c[1]]=c[3]);return typeof c[2]==="function"?c[2].call(a,
j[c[1]]):a}if(arguments.length===1&&typeof c==="string")return a.core.items[c];a.raiseError&&a.raiseError(this,"25081840","run","",new SyntaxError('Use the "new" keyword while creating a new FusionCharts object'))}var d={};this.__state={};if(arguments.length===1&&typeof arguments[0]==="object")d=arguments[0];else if(a.parseCommands(d,i.stat,arguments),a.core.options.sensePreferredRenderer&&d.swfUrl&&d.swfUrl.match&&!d.swfUrl.match(/[^a-z0-9]+/ig))d.type=d.swfUrl;arguments.length>1&&typeof arguments[arguments.length-
1]==="object"&&(delete d[i.stat[arguments.length-1]],a.extend(d,arguments[arguments.length-1]));this.id=typeof d.id==="undefined"?this.id=a.uniqueId():d.id;this.args=d;if(a.core.items[this.id]instanceof a.core)a.raiseWarning(this,"06091847","param","",Error('A FusionChart oject with the specified id "'+this.id+'" already exists. Renaming it to '+(this.id=a.uniqueId())));if(d.type&&d.type.toString){if(!a.renderer.userSetDefault&&(f||b))d.renderer=d.renderer||"javascript";d.swfUrl=(a.core.options.swfSrcPath||
d.swfSrcPath||a.core.options.scriptBaseUri).replace(/\/\s*$/g,"")+"/"+d.type.replace(/\.swf\s*?$/ig,"")+".swf"}a.parsePolicies(this,a.policies,d);this.attributes.id=this.id;this.resizeTo(d.width,d.height,!0);a.raiseEvent("BeforeInitialize",d,this);a.core.items[this.id]=this;a.raiseEvent("Initialized",d,this);return this};a.core.prototype={};a.core.prototype.constructor=a.core;a.extend(a.core,{id:"FusionCharts",version:[3,2,4,"release",8565],items:{},options:{sensePreferredRenderer:!0},getObjectReference:function(b){return a.core.items[b].ref}},
!1);window.FusionCharts=a.core;window.FusionMaps&&window.FusionMaps.legacy?a.core(["private","modules.core.geo",window.FusionMaps.legacy,window.FusionMaps.version]):!/loaded|complete/.test(document.readyState)&&!document.loaded&&function(){function b(){if(!arguments.callee.done)arguments.callee.done=!0,k&&clearInterval(k),window.FusionMaps&&window.FusionMaps.legacy&&a.core(["private","modules.core.geo",window.FusionMaps.legacy,window.FusionMaps.version]),window.FusionMaps=a.core}document.addEventListener?
document.addEventListener("DOMContentLoaded",b,!1):document.attachEvent&&window.attachEvent("onLoad",b);if(/msie/i.test(navigator.userAgent)&&!window.opera)try{document.write("<script id=__ie_onload defer src=javascript:void(0)><\/script>"),document.getElementById("__ie_onload").onreadystatechange=function(){this.readyState=="complete"&&b()}}catch(d){}if(/WebKit/i.test(navigator.userAgent))var k=setInterval(function(){/loaded|complete/.test(document.readyState)&&b()},10);window.onload=function(d){return function(){b();
d&&d.call&&d.call(window)}}(window.onload)}();window.FusionMaps=a.core}})();
(function(){var a=FusionCharts(["private","EventManager"]);if(a!==void 0){window.FusionChartsEvents={BeforeInitialize:"beforeinitialize",Initialized:"initialized",Loaded:"loaded",BeforeRender:"beforerender",Rendered:"rendered",DataLoadRequested:"dataloadrequested",DataLoadRequestCancelled:"dataloadrequestcancelled",DataLoadRequestCompleted:"dataloadrequestcompleted",BeforeDataUpdate:"beforedataupdate",DataUpdateCancelled:"dataupdatecancelled",DataUpdated:"dataupdated",DataLoadCancelled:"dataloadcancelled",
DataLoaded:"dataloaded",DataLoadError:"dataloaderror",NoDataToDisplay:"nodatatodisplay",DataXMLInvalid:"dataxmlinvalid",InvalidDataError:"invaliddataerror",DrawComplete:"drawcomplete",Resized:"resized",BeforeDispose:"beforedispose",Disposed:"disposed"};var j=function(a,b,e,c){try{a[0].call(b,e,c||{})}catch(d){setTimeout(function(){throw d;},0)}},i=function(f,b,e){if(f instanceof Array)for(var c=0,d;c<f.length;c+=1){if(f[c][1]===b.sender||f[c][1]===void 0)if(d=f[c][1]===b.sender?b.sender:a.core,j(f[c],
d,b,e),b.detached===!0)f.splice(c,1),c-=1,b.detached=!1;if(b.cancelled===!0)break}},h={unpropagator:function(){return(this.cancelled=!0)===!1},detacher:function(){return(this.detached=!0)===!1},undefaulter:function(){return(this.prevented=!0)===!1},listeners:{},lastEventId:0,addListener:function(f,b,e){if(f instanceof Array)for(var c=0;c<f.length;c+=1)h.addListener(f[c],b,e);else typeof f!=="string"?a.raiseError(e||a.core,"03091549","param","::EventTarget.addListener",Error("Unspecified Event Type")):
typeof b!=="function"?a.raiseError(e||a.core,"03091550","param","::EventTarget.addListener",Error("Invalid Event Listener")):(f=f.toLowerCase(),h.listeners[f]instanceof Array||(h.listeners[f]=[]),h.listeners[f].push([b,e]))},removeListener:function(f,b,e){var c;if(typeof b!=="function")a.raiseError(e||a.core,"03091560","param","::EventTarget.removeListener",Error("Invalid Event Listener"));else if(f instanceof Array)for(c=0;c<f.length;c+=1)h.removeListener(f[c],b,e);else if(typeof f!=="string")a.raiseError(e||
a.core,"03091559","param","::EventTarget.removeListener",Error("Unspecified Event Type"));else if(f=f.toLowerCase(),f=h.listeners[f],f instanceof Array)for(c=0;c<f.length;c+=1)f[c][0]===b&&f[c][1]===e&&(f.splice(c,1),c-=1)},triggerEvent:function(f,b,e,c,d){if(typeof f!=="string")a.raiseError(b,"03091602","param","::EventTarget.dispatchEvent",Error("Invalid Event Type"));else{f=f.toLowerCase();b={eventType:f,eventId:h.lastEventId+=1,sender:b||Error("Orphan Event"),cancel:!1,stopPropagation:this.unpropagator,
prevented:!1,preventDefault:this.undefaulter,detached:!1,detachHandler:this.detacher};if(c)b.originalEvent=c;i(h.listeners[f],b,e);i(h.listeners["*"],b,e);d&&b.prevented===!1&&j(d,b.sender,b,e);return!0}}};a.raiseEvent=function(a,b,e,c,d){return h.triggerEvent(a,e,b,c,d)};a.addEventListener=function(a,b){return h.addListener(a,b)};a.removeEventListener=function(a,b){return h.removeListener(a,b)};a.extend(a.core,{addEventListener:a.addEventListener,removeEventListener:a.removeEventListener},!1);a.extend(a.core,
{addEventListener:function(a,b){return h.addListener(a,b,this)},removeEventListener:function(a,b){return h.removeListener(a,b,this)}},!0);a.addEventListener("BeforeDispose",function(a){var b,e;for(b in h.listeners)for(e=0;e<h.listeners[b].length;e+=1)h.listeners[b][e][1]===a.sender&&h.listeners[b].splice(e,1)})}})();
(function(){var a=FusionCharts(["private","ErrorHandler"]);if(a!==void 0){var j={type:"TypeException",range:"ValueRangeException",impl:"NotImplementedException",param:"ParameterException",run:"RuntimeException",comp:"DesignTimeError",undefined:"UnspecifiedException"},i=function(f,b,e,c,d,k){var u="#"+b+" "+(f?f.id:"unknown-source")+c+" "+k+" >> ";d instanceof Error?(d.name=j[e],d.module="FusionCharts"+c,d.level=k,d.message=u+d.message,u=d.message,window.setTimeout(function(){throw d;},0)):u+=d;b=
{id:b,nature:j[e],source:"FusionCharts"+c,message:u};a.raiseEvent(k,b,f);if(typeof window["FC_"+k]==="function")window["FC_"+k](b)};a.raiseError=function(a,b,e,c,d){i(a,b,e,c,d,"Error")};a.raiseWarning=function(a,b,e,c,d){i(a,b,e,c,d,"Warning")};var h={outputHelpers:{text:function(a,b){h.outputTo("#"+a.eventId+" ["+(a.sender.id||a.sender).toString()+'] fired "'+a.eventType+'" event. '+(a.eventType==="error"||a.eventType==="warning"?b.message:""))},event:function(a,b){this.outputTo(a,b)},verbose:function(a,
b){h.outputTo(a.eventId,a.sender.id,a.eventType,b)}},outputHandler:function(f,b){typeof h.outputTo!=="function"?a.core.debugMode.outputFailed=!0:(a.core.debugMode.outputFailed=!1,h.currentOutputHelper(f,b))},currentOutputHelper:void 0,outputTo:void 0,enabled:!1};h.currentOutputHelper=h.outputHelpers.text;a.extend(a.core,{debugMode:{syncStateWithCharts:!0,outputFormat:function(a){if(a&&typeof a.toLowerCase==="function"&&typeof h.outputHelpers[a=a.toLowerCase()]==="function")return h.currentOutputHelper=
h.outputHelpers[a],!0;return!1},outputTo:function(f){typeof f==="function"?h.outputTo=f:f===null&&(a.core.debugMode.enabled(!1),delete h.outputTo)},enabled:function(f,b,e){var c;if(typeof f==="object"&&arguments.length===1)c=f,f=c.state,b=c.outputTo,e=c.outputFormat;if(typeof f==="function"){if(typeof b==="string"&&(arguments.length===2||c))e=b;b=f;f=!0}if(typeof f==="boolean"&&f!==h.enabled)a.core[(h.enabled=f)?"addEventListener":"removeEventListener"]("*",h.outputHandler);if(typeof b==="function")h.outputTo=
b;a.core.debugMode.outputFormat(e);return h.enabled},_enableFirebugLite:function(){window.console&&window.console.firebug?a.core.debugMode.enabled(console.log,"verbose"):a.loadScript("firebug-lite.js",function(){a.core.debugMode.enabled(console.log,"verbose")},"{ startOpened: true }")}}},!1)}})();
(function(){var a=FusionCharts(["private","modules.mantle.ajax"]);if(a){var j=window,i=parseFloat(navigator.appVersion.split("MSIE")[1]),h=i>=5.5&&i<=7?!0:!1,f=j.location.protocol==="file:",b=j.ActiveXObject,e=(!b||!f)&&j.XMLHttpRequest,c={objects:0,xhr:0,requests:0,success:0,failure:0,idle:0},d=function(){var a;if(e)return d=function(){c.xhr++;return new e},d();try{a=new b("Msxml2.XMLHTTP"),d=function(){c.xhr++;return new b("Msxml2.XMLHTTP")}}catch(f){try{a=new b("Microsoft.XMLHTTP"),d=function(){c.xhr++;
return new b("Microsoft.XMLHTTP")}}catch(g){a=!1}}return a},j=a.ajax=function(a,d){this.onSuccess=a;this.onError=d;this.open=!1;c.objects++;c.idle++};j.stats=function(d){return d?c[d]:a.extend({},c)};j.prototype.headers={"If-Modified-Since":"Sat, 29 Oct 1994 19:43:31 GMT","X-Requested-With":"XMLHttpRequest","X-Requested-By":"FusionCharts",Accept:"text/plain, */*"};j.prototype.get=function(b,e){var g=this,l=g.xmlhttp,r=g.headers,m=g.onError,p=g.onSuccess,n;if(!l||h)l=d(),g.xmlhttp=l;l.onreadystatechange=
function(){try{if(l.readyState===4)!l.status&&f||l.status>=200&&l.status<300||l.status===304||l.status===1223||l.status===0?(p&&p(l.responseText,g,e,b),c.success++):m&&(m(Error("XmlHttprequest Error"),g,e,b),c.failure++),c.idle--,g.open=!1}catch(a){m&&m(a,g,e,b),c.failure++}};try{l.overrideMimeType&&l.overrideMimeType("text/plain");l.open("GET",b,!0);for(n in r)l.setRequestHeader(n,r[n]);l.send(null);c.requests++;c.idle++;g.open=!0}catch(i){a.raiseError(a.core,"1110111515A","run","XmlHttprequest Error",
i.message)}return l};j.prototype.abort=function(){var a=this.xmlhttp;this.open=!1;return a&&typeof a.abort==="function"&&a.readyState&&a.readyState!==0&&a.abort()};j.prototype.dispose=function(){this.open&&this.abort();delete this.onError;delete this.onSuccess;delete this.xmlhttp;delete this.open;c.objects--;return null}}})();
(function(){var a=FusionCharts(["private","modules.mantle.runtime;1.1"]);if(a!==void 0){var j=/(^|[\/\\])(fusioncharts\.js|fusioncharts\.debug\.js|fusioncharts\.core\.js|fusioncharts\.min\.js)([\?#].*)?$/ig;a.getScriptBaseUri=function(a){var d=document.getElementsByTagName("script"),b=d.length,k,c;for(c=0;c<b;c+=1)if(k=d[c].getAttribute("src"),!(k===void 0||k===null||k.match(a)===null))return k.replace(a,"$1")};a.core.options.scriptBaseUri=function(){var d=a.getScriptBaseUri(j);if(d===void 0)return a.raiseError(FusionCharts,
"1603111624","run",">GenericRuntime~scriptBaseUri","Unable to locate FusionCharts script source location (URL)."),"";return d}();var i=/[\\\"<>;&]/,h=/^[^\S]*?(sf|f|ht)(tp|tps):\/\//i,f=FusionChartsEvents.ExternalResourceLoad="externalresourceload",b={},e={},c={},d={};a.isXSSSafe=function(a,d){if(d&&h.exec(a)!==null)return!1;return i.exec(a)===null};a.loadScript=function(k,g,p,u,l){if(!k)return!1;var i=g&&g.success||g,h=g&&g.failure,j,w={type:"script",success:!1},v=function(){d[j]=clearTimeout(d[j]);
w.success?i&&i(k,j):h&&h(k,j);a.raiseEvent(f,w,a.core)},l=l?"":a.core.options.scriptBaseUri;j=l+k;a.isXSSSafe(j,!1)||(j=typeof window.encodeURIComponent==="function"?window.encodeURIComponent(j):window.escape(j));w.path=l;w.src=j;w.file=k;if(c[j]===!0&&u)return w.success=!0,w.notReloaded=!0,typeof g==="function"&&(g(),a.raiseEvent(f,w,a.core)),!0;if(b[j]&&u)return!1;b[j]=!0;e[j]&&e[j].parentNode&&e[j].parentNode.removeChild(e[j]);g=e[j]=document.createElement("script");g.type="text/javascript";g.src=
j;p&&(g.innerHTML=p);if(typeof i==="function")c[j]=!1,d[j]=clearTimeout(d[j]),g.onload=function(){c[j]=!0;w.success=!0;v()},g.onerror=function(){c[j]=!1;b[j]=!1;v()},g.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded")c[j]=!0,w.success=!0,v()};document.getElementsByTagName("head")[0].appendChild(g);typeof h==="function"&&(d[j]=setTimeout(function(){c[j]||v()},a.core.options.html5ResourceLoadTimeout||15E3));return!0};a.capitalizeString=function(a,d){return a?
a.replace(d?/(^|\s)([a-z])/g:/(^|\s)([a-z])/,function(a,d,b){return d+b.toUpperCase()}):a};var k=a.purgeDOM=function(a){var d=a.attributes,b,c;if(d)for(b=d.length-1;b>=0;b-=1)c=d[b].name,typeof a[c]==="function"&&(a[c]=null);if(d=a.childNodes){d=d.length;for(b=0;b<d;b+=1)k(a.childNodes[b])}},u=function(a,d,b){for(var k in a){var c;if(a[k]instanceof Array)d[a[k][0]]=b[k];else for(c in a[k])d[a[k][c][0]]=b[k][c]}},g=/[^\%\d]*$/ig,l=/^(FusionCharts|FusionWidgets|FusionMaps)/;a.extend(a.core,{dispose:function(){a.raiseEvent("BeforeDispose",
{},this);a.renderer.dispose(this);delete a.core.items[this.id];a.raiseEvent("Disposed",{},this);for(var d in this)delete this[d]},clone:function(d,b){var k=typeof d,c={},g=a.extend({},this.args,!1,!1);u(a.policies,g,this);u(a.renderer.getRendererPolicy(this.options.renderer),g,this);delete g.id;delete g.animate;delete g.stallLoad;c.link=g.link;g=a.extend({},g,!1,!1);g.link=c.link;switch(k){case "object":a.extend(g,d);break;case "boolean":b=d}return b?g:new a.core(g)},isActive:function(){if(!this.ref||
document.getElementById(this.id)!==this.ref||typeof this.ref.signature!=="function")return!1;try{return l.test(this.ref.signature())}catch(a){return!1}},resizeTo:function(d,b,k){var c={width:d,height:b};if(typeof d==="object")c.width=d.width,c.height=d.height,k=b;if(c.width&&typeof c.width.toString==="function")this.width=c.width.toString().replace(g,"");if(c.height&&typeof c.height.toString==="function")this.height=c.height.toString().replace(g,"");k!==!0&&a.renderer.resize(this,c)},chartType:function(a){var d=
this.src,b;if(typeof a==="string")this.src=a,this.isActive()&&this.render();return(b=(b=d.substring(d.indexOf(".swf"),0))?b:d).substring(b.lastIndexOf("/")+1).toLowerCase().replace(/^fcmap_/i,"")}},!0);window.getChartFromId=window.getMapFromId=function(d){a.raiseWarning(this,"11133001041","run","GenericRuntime~getObjectFromId()",'Use of deprecated getChartFromId() or getMapFromId(). Replace with "FusionCharts()" or FusionCharts.items[].');return a.core.items[d]instanceof a.core?a.core.items[d].ref:
window.swfobject.getObjectById(d)}}})();
(function(){var a=FusionCharts(["private","RendererManager"]);if(a!==void 0){a.policies.options.containerElementId=["renderAt",void 0];a.policies.options.renderer=["renderer",void 0];a.normalizeCSSDimension=function(a,b,c){var a=a===void 0?c.offsetWidth:a,b=b===void 0?c.offsetHeight:b,g;c.style.width=a=a.toString?a.toString():"0";c.style.height=b=b.toString?b.toString():"0";if(a.match(/^\s*\d*\.?\d*\%\s*$/)&&!a.match(/^\s*0\%\s*$/)&&c.offsetWidth===0)for(g=c;g=g.offsetParent;)if(g.offsetWidth>0){a=
(g.offsetWidth*parseFloat(a.match(/\d*/)[0])/100).toString();break}if(b.match(/^\s*\d*\.?\d*\%\s*$/)&&!b.match(/^\s*0\%\s*$/)&&c.offsetHeight<=20)for(g=c;g=g.offsetParent;)if(g.offsetHeight>0){b=(g.offsetHeight*parseFloat(b.match(/\d*/)[0])/100).toString();break}g={width:a.replace?a.replace(/^\s*(\d*\.?\d*)\s*$/ig,"$1px"):a,height:b.replace?b.replace(/^\s*(\d*\.?\d*)\s*$/ig,"$1px"):b};c.style.width=g.width;c.style.height=g.height;return g};var j=function(){a.raiseError(this,"25081845","run","::RendererManager",
Error("No active renderer"))},i={undefined:{render:j,remove:j,update:j,resize:j,config:j,policies:{}}},h={},f=a.renderer={register:function(d,b){if(!d||typeof d.toString!=="function")throw"#03091436 ~renderer.register() Invalid value for renderer name.";d=d.toString().toLowerCase();if(i[d]!==void 0)return a.raiseError(a.core,"03091438","param","::RendererManager>register",'Duplicate renderer name specified in "name"'),!1;i[d]=b;return!0},userSetDefault:!1,setDefault:function(d){if(!d||typeof d.toString!==
"function")return a.raiseError(a.core,"25081731","param","::RendererManager>setDefault",'Invalid renderer name specified in "name"'),!1;if(i[d=d.toString().toLowerCase()]===void 0)return a.raiseError(a.core,"25081733","range","::RendererManager>setDefault","The specified renderer does not exist."),!1;this.userSetDefault=!1;a.policies.options.renderer=["renderer",d];return!0},notifyRender:function(d){var b=a.core.items[d&&d.id];(!b||d.success===!1&&!d.silent)&&a.raiseError(a.core.items[d.id],"25081850",
"run","::RendererManager",Error("There was an error rendering the chart. Enable FusionCharts JS debugMode for more information."));if(b.ref=d.ref)if(d.ref.FusionCharts=a.core.items[d.id],b.options.containerBackgroundColor)d.ref.style&&(d.ref.style.backgroundColor=b.options.containerBackgroundColor);a.raiseEvent("internal.DOMElementCreated",d,b)},protectedMethods:{options:!0,attributes:!0,src:!0,ref:!0,constructor:!0,signature:!0,link:!0},getRenderer:function(a){return i[a]},getRendererPolicy:function(a){a=
i[a].policies;return typeof a==="object"?a:{}},currentRendererName:function(){return a.policies.options.renderer[1]},update:function(a){h[a.id].update.apply(a,Array.prototype.slice.call(arguments,1))},render:function(a){h[a.id].render.apply(a,Array.prototype.slice.call(arguments,1))},remove:function(a){h[a.id].remove.apply(a,Array.prototype.slice.call(arguments,1))},resize:function(a){h[a.id].resize.apply(a,Array.prototype.slice.call(arguments,1))},config:function(a){h[a.id].config.apply(a,Array.prototype.slice.call(arguments,
1))},dispose:function(a){h[a.id].dispose.apply(a,Array.prototype.slice.call(arguments,1))}},b=function(d){return function(){if(this.ref===void 0||this.ref===null||typeof this.ref[d]!=="function")a.raiseError(this,"25081617","run","~"+d+"()","ExternalInterface call failed. Check whether chart has been rendered.");else return this.ref[d].apply(this.ref,arguments)}};a.addEventListener("BeforeInitialize",function(d){var d=d.sender,b;if(typeof d.options.renderer==="string"&&i[d.options.renderer.toLowerCase()]===
void 0)d.options.renderer=a.policies.options.renderer[1];d.options.renderer=d.options.renderer.toLowerCase();h[d.id]=i[d.options.renderer];if(h[d.id].initialized!==!0&&typeof h[d.id].init==="function")h[d.id].init(),h[d.id].initialized=!0;a.parsePolicies(d,h[d.id].policies||{},d.args);for(var c in h[d.id].prototype)d[c]=h[d.id].prototype[c];for(b in h[d.id].events)d.addEventListener(b,h[d.id].events[b])});a.addEventListener("Loaded",function(d){var c=d.sender,d=d.sender.ref;c instanceof a.core&&delete c.__state.rendering;
if(!(d===void 0||d===null||typeof d.getExternalInterfaceMethods!=="function")){var e;try{e=d.getExternalInterfaceMethods(),e=typeof e==="string"?e.split(","):[]}catch(g){e=[],a.raiseError(c,"13111126041","run","RendererManager^Loaded",Error("Error while retrieving data from the chart-object."+(g.message&&g.message.indexOf("NPObject")>=0?" Possible cross-domain security restriction.":"")))}for(d=0;d<e.length;d+=1)c[e[d]]===void 0&&(c[e[d]]=b(e[d]))}});var e=function(a,b){if(typeof a[b]==="function")return function(){return a[b].apply(a,
arguments)};return a[b]};a.addEventListener("loaded",function(d){var b=d.sender;if(b.ref){var c=a.renderer.protectedMethods,g=a.renderer.getRenderer(b.options.renderer).protectedMethods,f;for(f in d.sender)if(g&&!c[f]&&!(g[f]||b.ref[f]!==void 0))try{b.ref[f]=e(d.sender,f)}catch(i){}}});var c=function(a,b){var c=document.getElementById(a),g=b.getAttribute("id");if(c===null)return!1;if(a===g)return!0;for(var g=b.getElementsByTagName("*"),e=0;e<g.length;e+=1)if(g[e]===c)return!1;return!0};a.extend(a.core,
{render:function(d){var b,e;((b=window[this.id])&&b.FusionCharts&&b.FusionCharts===this||(b=this.ref)&&b.FusionCharts&&b.FusionCharts===this)&&a.renderer.dispose(this);window[this.id]!==void 0&&a.raiseError(this,"25081843","comp",".render",Error("#25081843:IECompatibility() Chart Id is same as a JavaScript variable name. Variable naming error. Please use unique name for chart JS variable, chart-id and container id."));e=this.options.insertMode.toLowerCase()||"replace";if(d===void 0)d=this.options.containerElementId;
typeof d==="string"&&(d=document.getElementById(d));if(d===void 0||d===null)return a.raiseError(this,"03091456","run",".render()",Error("Unable to find the container DOM element.")),this;if(c(this.id,d))return a.raiseError(this,"05102109","run",".render()",Error("A duplicate object already exists with the specific Id: "+this.id)),this;b=document.createElement(this.options.containerElementType||"span");b.setAttribute("id",this.id);if(e!=="append"&&e!=="prepend")for(;d.hasChildNodes();)d.removeChild(d.firstChild);
e==="prepend"&&d.firstChild?d.insertBefore(b,d.firstChild):d.appendChild(b);this.options.containerElement=d;this.options.containerElementId=d.id;if(e=b.style)e.lineHeight="100%",e.display="inline-block",e.zoom="1",e["*DISPLAY"]="inline";a.normalizeCSSDimension(this.width,this.height,b);this.__state.rendering=!0;a.raiseEvent("BeforeRender",{container:d,width:this.width,height:this.height,renderer:this.options.renderer},this);a.renderer.render(this,b,a.renderer.notifyRender);return this},remove:function(){a.renderer.remove(this);
return this},configure:function(d,b){var c;d&&(typeof d==="string"?(c={},c[d]=b):c=d,a.renderer.config(this,c))}},!0);a.extend(a.core,{setCurrentRenderer:function(){var a=f.setDefault.apply(f,arguments);f.userSetDefault=!0;return a},getCurrentRenderer:function(){return f.currentRendererName.apply(f,arguments)},render:function(){var d=["swfUrl","id","width","height","renderAt","dataSource","dataFormat"],b={},c;if(arguments[0]instanceof a.core)return arguments[0].render(),arguments[0];for(c=0;c<arguments.length&&
c<d.length;c+=1)b[d[c]]=arguments[c];typeof arguments[arguments.length-1]==="object"&&(delete b[d[c-1]],a.extend(b,arguments[arguments.length-1]));if(b.dataFormat===void 0)b.dataFormat=FusionChartsDataFormats.XMLURL;return(new a.core(b)).render()}},!1)}})();
(function(){var a=FusionCharts(["private","DataHandlerManager"]);if(a!==void 0){window.FusionChartsDataFormats={};var j=a.transcoders={},i={},h={},f=/url$/i,b=function(d,b,c,g){var e=!1,f=c.obj,i=c.format,c=c.silent;a.raiseEvent("DataLoadRequestCompleted",{source:"XmlHttpRequest",url:g,data:d,dataFormat:i,cancelDataLoad:function(){e=!0;b.abort();this.cancelDataLoad=function(){return!1};return!0},xmlHttpRequestObject:b.xhr},f);e!==!0?f.setChartData(d,i,c):a.raiseEvent("DataLoadCancelled",{source:"XmlHttpRequest",
url:g,dataFormat:i,xmlHttpRequestObject:b.xhr},f)},e=function(d,b,c,g){c=c.obj;d={source:"XmlHttpRequest",url:g,xmlHttpRequestObject:b.xhr,error:d,httpStatus:b.xhr&&b.xhr.status?b.xhr.status:-1};a.raiseEvent("DataLoadError",d,c);typeof window.FC_DataLoadError==="function"&&window.FC_DataLoadError(c.id,d)};a.policies.options.dataSource=["dataSource",void 0];a.policies.options.dataFormat=["dataFormat",void 0];a.policies.options.dataConfiguration=["dataConfiguration",void 0];a.policies.options.showDataLoadingMessage=
["showDataLoadingMessage",!0];a.addDataHandler=function(d,b){if(typeof d!=="string"||j[d.toLowerCase()]!==void 0)a.raiseError(a.core,"03091606","param","::DataManager.addDataHandler",Error("Invalid Data Handler Name"));else{var c={},g=d.toLowerCase();j[g]=b;b.name=d;c["set"+d+"Url"]=function(a){return this.setChartDataUrl(a,d)};c["set"+d+"Data"]=function(a,b){return this.setChartData(a,d,!1,b)};c["get"+d+"Data"]=function(){return this.getChartData(d)};window.FusionChartsDataFormats[d]=g;window.FusionChartsDataFormats[d+
"URL"]=g+"URL";a.extend(a.core,c,!0)}};a.addEventListener("BeforeInitialize",function(a){a=a.sender;i[a.id]="";h[a.id]={};if(a.options.dataSource!==void 0&&typeof a.options.dataFormat==="string")a.__state.dataSetDuringConstruction=!0,a.setChartData(a.options.dataSource,a.options.dataFormat)});a.addEventListener("BeforeDispose",function(a){var b=a.sender;delete i[a.sender.id];delete h[a.sender.id];b&&b.__state&&b.__state.dhmXhrObj&&b.__state.dhmXhrObj.abort()});a.extend(a.core,{setChartDataUrl:function(d,
c,i){if(c===void 0||c===null||typeof c.toString!=="function")a.raiseError(a.core,"03091609","param",".setChartDataUrl",Error("Invalid Data Format"));else{var c=c.toString().toLowerCase(),g,l=this,h=l.options&&l.options.renderer==="flash"&&l.options.useLegacyXMLTransport||!1;f.test(c)?g=c.slice(0,-3):(g=c,c+="url");a.raiseEvent("DataLoadRequested",{source:"XmlHttpRequest",url:d,dataFormat:g,cancelDataLoadRequest:function(){h=!0;a.raiseEvent("DataLoadRequestCancelled",{source:"XmlHttpRequest",url:d,
dataFormat:g},l);try{this.__state&&this.__state.dhmXhrObj&&this.__state.dhmXhrObj.abort()}catch(b){}this.cancelDataLoadRequest=function(){return!1};return!0}},l);if(h){if(this.__state&&this.__state.dhmXhrObj)try{this.__state.dhmXhrObj.abort()}catch(j){}}else{this.options.dataSource=d;if(!this.__state.dhmXhrObj)this.__state.dhmXhrObj=new a.ajax(b,e);this.__state.dhmXhrObj.get(typeof window.decodeURIComponent==="function"?window.decodeURIComponent(d):window.unescape(d),{obj:this,format:g,silent:i})}}},
setChartData:function(b,c,e){if(c===void 0||c===null||typeof c.toString!=="function")a.raiseError(a.core,"03091610","param",".setChartData",Error("Invalid Data Format"));else{var c=c.toString().toLowerCase(),g;if(f.test(c))this.setChartDataUrl(b,c,e);else{this.options.dataSource=b;g=c;this.options.dataFormat=c;var c=j[g],l=!1;if(typeof c==="undefined")a.raiseError(a.core,"03091611","param",".setChartData",Error("Data Format not recognized"));else if(c=c.encode(b,this,this.options.dataConfiguration)||
{},c.format=c.dataFormat=g,c.dataSource=b,c.cancelDataUpdate=function(){l=!0;this.cancelDataUpdate=function(){return!1};return!0},a.raiseEvent("BeforeDataUpdate",c,this),delete c.cancelDataUpdate,l===!0)a.raiseEvent("DataUpdateCancelled",c,this);else{i[this.id]=c.data||"";h[this.id]={};if(e!==!0)this.options.safeMode===!0&&this.__state.rendering===!0&&!this.isActive()?(this.__state.updatePending=c,a.raiseWarning(this,"23091255","run","::DataHandler~update","Renderer update was postponed due to async loading.")):
(delete this.__state.updatePending,a.renderer.update(this,c));this.__state.dataReady=void 0;a.raiseEvent("DataUpdated",c,this)}}}},getChartData:function(b,c){var d;var e;if(b===void 0||typeof b.toString!=="function"||(e=j[b=b.toString().toLowerCase()])===void 0)a.raiseError(this,"25081543","param","~getChartData()",Error('Unrecognized data-format specified in "format"'));else return d=typeof h[this.id][b]==="object"?h[this.id][b]:h[this.id][b]=e.decode(i[this.id],this,this.options.dataConfiguration),
e=d,Boolean(c)===!0?e:e.data},dataReady:function(){return this.__state.dataReady}},!0);a.extend(a.core,{transcodeData:function(b,c,e,g,f){if(!c||typeof c.toString!=="function"||!e||typeof e.toString!=="function"||j[e=e.toString().toLowerCase()]===void 0||j[c=c.toString().toLowerCase()]===void 0)a.raiseError(this,"14090217","param","transcodeData()",Error("Unrecognized data-format specified during transcoding."));else{b=j[c].encode(b,this,f);e=j[e].decode(b.data,this,f);if(!(e.error instanceof Error))e.error=
b.error;return g?e:e.data}}},!1);a.addEventListener("Disposed",function(a){delete h[a.sender.id]});a.addEventListener("Loaded",function(b){b=b.sender;b instanceof a.core&&b.__state.updatePending!==void 0&&(a.renderer.update(b,b.__state.updatePending),delete b.__state.updatePending)});a.addEventListener("NoDataToDisplay",function(a){a.sender.__state.dataReady=!1});var c=a._interactiveCharts={selectscatter:[!0,!1],dragcolumn2d:[!0,!0],dragarea:[!0,!0],dragline:[!0,!0],dragnode:[!0,!0]};a.addEventListener("Loaded",
function(b){var b=b.sender,e=b.__state,f,g;if(b.chartType&&c[b.chartType()]&&c[b.chartType()][0]){for(f in a.transcoders)g=a.transcoders[f].name,g="get"+g+"Data",b[g]=function(b,c){return function(d){return d===!1?c.apply(this):this.ref.getUpdatedXMLData?a.core.transcodeData(this.ref.getUpdatedXMLData(),"xml",b):this.getData?this.getData(b):c.apply(this)}}(f,b.constructor.prototype[g]),b[g]._dynamicdatarouter=!0;e.dynamicDataRoutingEnabled=!0}else if(e.dynamicDataRoutingEnabled){for(f in a.transcoders)g=
a.transcoders[f].name,g="get"+g+"Data",b.hasOwnProperty(g)&&b[g]._dynamicdatarouter&&delete b[g];e.dynamicDataRoutingEnabled=!1}})}})();
var swfobject=window.swfobject=function(){function a(){if(!B){try{var a=q.getElementsByTagName("body")[0].appendChild(q.createElement("span"));a.parentNode.removeChild(a)}catch(b){return}B=!0;for(var a=F.length,c=0;c<a;c++)F[c]()}}function j(a){B?a():F[F.length]=a}function i(a){if(typeof v.addEventListener!=t)v.addEventListener("load",a,!1);else if(typeof q.addEventListener!=t)q.addEventListener("load",a,!1);else if(typeof v.attachEvent!=t)r(v,"onload",a);else if(typeof v.onload=="function"){var b=
v.onload;v.onload=function(){b();a()}}else v.onload=a}function h(){var a=q.getElementsByTagName("body")[0],b=q.createElement(x);b.setAttribute("type",E);var c=a.appendChild(b);if(c){var d=0;(function(){if(typeof c.GetVariable!=t){var g;try{g=c.GetVariable("$version")}catch(e){}if(g)g=g.split(" ")[1].split(","),o.pv=[parseInt(g[0],10),parseInt(g[1],10),parseInt(g[2],10)]}else if(d<10){d++;setTimeout(arguments.callee,10);return}a.removeChild(b);c=null;f()})()}else f()}function f(){var a=y.length;if(a>
0)for(var g=0;g<a;g++){var f=y[g].id,p=y[g].callbackFn,k=y[g].userData||{};k.success=!1;k.id=f;if(o.pv[0]>0){var i=l(f);if(i)if(m(y[g].swfVersion)&&!(o.wk&&o.wk<312)){if(n(f,!0),p)k.success=!0,k.ref=b(f),p(k)}else if(y[g].expressInstall&&e()){k={};k.data=y[g].expressInstall;k.width=i.getAttribute("width")||"0";k.height=i.getAttribute("height")||"0";if(i.getAttribute("class"))k.styleclass=i.getAttribute("class");if(i.getAttribute("align"))k.align=i.getAttribute("align");for(var h={},i=i.getElementsByTagName("param"),
j=i.length,r=0;r<j;r++)i[r].getAttribute("name").toLowerCase()!="movie"&&(h[i[r].getAttribute("name")]=i[r].getAttribute("value"));c(k,h,f,p)}else d(i),p&&p(k)}else if(n(f,!0),p){if((f=b(f))&&typeof f.SetVariable!=t)k.success=!0,k.ref=f;p(k)}}}function b(a){var b,c=null;if(!document.embeds||!(b=document.embeds[a]))if(!((b=l(a))&&b.nodeName=="OBJECT"))b=window[a];if(!b)return c;typeof b.SetVariable!=t?c=b:(a=b.getElementsByTagName(x)[0])&&(c=a);return c}function e(){return!G&&m("6.0.65")&&(o.win||
o.mac)&&!(o.wk&&o.wk<312)}function c(a,b,c,d){G=!0;J=d||null;L={success:!1,id:c};var g=l(c);if(g){g.nodeName=="OBJECT"?(D=k(g),H=null):(D=g,H=c);a.id=w;if(typeof a.width==t||!/%$/.test(a.width)&&parseInt(a.width,10)<310)a.width="310";if(typeof a.height==t||!/%$/.test(a.height)&&parseInt(a.height,10)<137)a.height="137";q.title=q.title.slice(0,47)+" - Flash Player Installation";d=o.ie&&o.win?"ActiveX":"PlugIn";d="MMredirectURL="+v.location.toString().replace(/&/g,"%26")+"&MMplayerType="+d+"&MMdoctitle="+
q.title;typeof b.flashvars!=t?b.flashvars+="&"+d:b.flashvars=d;if(o.ie&&o.win&&g.readyState!=4)d=q.createElement("div"),c+="SWFObjectNew",d.setAttribute("id",c),g.parentNode.insertBefore(d,g),g.style.display="none",function(){g.readyState==4?g.parentNode.removeChild(g):setTimeout(arguments.callee,10)}();u(a,b,c)}}function d(a){if(o.ie&&o.win&&a.readyState!=4){var b=q.createElement("div");a.parentNode.insertBefore(b,a);b.parentNode.replaceChild(k(a),b);a.style.display="none";(function(){a.readyState==
4?a.parentNode.removeChild(a):setTimeout(arguments.callee,10)})()}else a.parentNode.replaceChild(k(a),a)}function k(a){var b=q.createElement("div");if(o.win&&o.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName(x)[0])if(a=a.childNodes)for(var c=a.length,d=0;d<c;d++)!(a[d].nodeType==1&&a[d].nodeName=="PARAM")&&a[d].nodeType!=8&&b.appendChild(a[d].cloneNode(!0));return b}function u(a,b,c){var d,c=l(c);if(o.wk&&o.wk<312)return d;if(c){if(typeof a.id==t)a.id=c.id;if(o.ie&&o.win){var g="",e;for(e in a)if(a[e]!=
Object.prototype[e])e.toLowerCase()=="data"?b.movie=a[e]:e.toLowerCase()=="styleclass"?g+=' class="'+a[e]+'"':e.toLowerCase()!="classid"&&(g+=" "+e+'="'+a[e]+'"');e="";for(var f in b)b[f]!=Object.prototype[f]&&(e+='<param name="'+f+'" value="'+b[f]+'" />');c.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+g+">"+e+"</object>";I[I.length]=a.id;d=l(a.id)}else{f=q.createElement(x);f.setAttribute("type",E);for(var k in a)a[k]!=Object.prototype[k]&&(k.toLowerCase()=="styleclass"?
f.setAttribute("class",a[k]):k.toLowerCase()!="classid"&&f.setAttribute(k,a[k]));for(g in b)b[g]!=Object.prototype[g]&&g.toLowerCase()!="movie"&&(a=f,e=g,k=b[g],d=q.createElement("param"),d.setAttribute("name",e),d.setAttribute("value",k),a.appendChild(d));c.parentNode.replaceChild(f,c);d=f}}return d}function g(a){var b=l(a);if(b&&b.nodeName=="OBJECT")o.ie&&o.win?(b.style.display="none",function(){if(b.readyState==4){var c=l(a);if(c){for(var d in c)typeof c[d]=="function"&&(c[d]=null);c.parentNode.removeChild(c)}}else setTimeout(arguments.callee,
10)}()):b.parentNode.removeChild(b)}function l(a){var b=null;try{b=q.getElementById(a)}catch(c){}return b}function r(a,b,c){a.attachEvent(b,c);C[C.length]=[a,b,c]}function m(a){var b=o.pv,a=a.split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&b[1]==a[1]&&b[2]>=a[2]?!0:!1}function p(a,b,c,d){if(!o.ie||!o.mac){var g=q.getElementsByTagName("head")[0];if(g){c=c&&typeof c=="string"?c:"screen";d&&(K=z=null);if(!z||K!=
c)d=q.createElement("style"),d.setAttribute("type","text/css"),d.setAttribute("media",c),z=g.appendChild(d),o.ie&&o.win&&typeof q.styleSheets!=t&&q.styleSheets.length>0&&(z=q.styleSheets[q.styleSheets.length-1]),K=c;o.ie&&o.win?z&&typeof z.addRule==x&&z.addRule(a,b):z&&typeof q.createTextNode!=t&&z.appendChild(q.createTextNode(a+" {"+b+"}"))}}}function n(a,b){if(M){var c=b?"visible":"hidden";B&&l(a)?l(a).style.visibility=c:p("#"+a,"visibility:"+c)}}function s(a){return/[\\\"<>\.;]/.exec(a)!=null&&
typeof encodeURIComponent!=t?encodeURIComponent(a):a}var t="undefined",x="object",E="application/x-shockwave-flash",w="SWFObjectExprInst",v=window,q=document,A=navigator,N=!1,F=[function(){N?h():f()}],y=[],I=[],C=[],D,H,J,L,B=!1,G=!1,z,K,M=!0,o=function(){var a=typeof q.getElementById!=t&&typeof q.getElementsByTagName!=t&&typeof q.createElement!=t,b=A.userAgent.toLowerCase(),c=A.platform.toLowerCase(),d=c?/win/.test(c):/win/.test(b),c=c?/mac/.test(c):/mac/.test(b),b=/webkit/.test(b)?parseFloat(b.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,
"$1")):!1,g=!+"\u000b1",e=[0,0,0],f=null;if(typeof A.plugins!=t&&typeof A.plugins["Shockwave Flash"]==x){if((f=A.plugins["Shockwave Flash"].description)&&!(typeof A.mimeTypes!=t&&A.mimeTypes[E]&&!A.mimeTypes[E].enabledPlugin))N=!0,g=!1,f=f.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),e[0]=parseInt(f.replace(/^(.*)\..*$/,"$1"),10),e[1]=parseInt(f.replace(/^.*\.(.*)\s.*$/,"$1"),10),e[2]=/[a-zA-Z]/.test(f)?parseInt(f.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if(typeof v.ActiveXObject!=t)try{var k=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");
if(k){try{f=k.GetVariable("$version")}catch(p){}f&&(g=!0,f=f.split(" ")[1].split(","),e=[parseInt(f[0],10),parseInt(f[1],10),parseInt(f[2],10)])}}catch(i){}return{w3:a,pv:e,wk:b,ie:g,win:d,mac:c}}();(function(){o.w3&&((typeof q.readyState!=t&&q.readyState=="complete"||typeof q.readyState==t&&(q.getElementsByTagName("body")[0]||q.body))&&a(),B||(typeof q.addEventListener!=t&&q.addEventListener("DOMContentLoaded",a,!1),o.ie&&o.win&&(q.attachEvent("onreadystatechange",function(){q.readyState=="complete"&&
(q.detachEvent("onreadystatechange",arguments.callee),a())}),v==top&&function(){if(!B){try{q.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,0);return}a()}}()),o.wk&&function(){B||(/loaded|complete/.test(q.readyState)?a():setTimeout(arguments.callee,0))}(),i(a)))})();(function(){o.ie&&o.win&&window.attachEvent("onunload",function(){for(var a=C.length,b=0;b<a;b++)C[b][0].detachEvent(C[b][1],C[b][2]);a=I.length;for(b=0;b<a;b++)g(I[b]);for(var c in o)o[c]=null;o=null;for(var d in swfobject)swfobject[d]=
null;swfobject=null})})();return{FusionChartsModified:!0,registerObject:function(a,b,c,d,g){var e=g||{};if(o.w3&&a&&b)e.id=a,e.swfVersion=b,e.expressInstall=c,e.callbackFn=d,e.userData=g,y[y.length]=e,n(a,!1);else if(d)e.success=!1,e.id=a,d(e)},getObjectById:function(a){if(o.w3)return b(a)},embedSWF:function(a,b,d,g,f,k,p,i,h,l,r){var s=r||{};s.success=!1;s.id=b;o.w3&&!(o.wk&&o.wk<312)&&a&&b&&d&&g&&f?(n(b,!1),j(function(){d+="";g+="";var j={};if(h&&typeof h===x)for(var r in h)j[r]=h[r];j.data=a;j.width=
d;j.height=g;r={};if(i&&typeof i===x)for(var o in i)r[o]=i[o];if(p&&typeof p===x)for(var q in p)typeof r.flashvars!=t?r.flashvars+="&"+q+"="+p[q]:r.flashvars=q+"="+p[q];if(m(f))o=u(j,r,b),j.id==b&&n(b,!0),s.success=!0,s.ref=o;else if(k&&e()){j.data=k;c(j,r,b,l);return}else n(b,!0);l&&l(s)})):l&&l(s)},switchOffAutoHideShow:function(){M=!1},ua:o,getFlashPlayerVersion:function(){return{major:o.pv[0],minor:o.pv[1],release:o.pv[2]}},hasFlashPlayerVersion:m,createSWF:function(a,b,c){if(o.w3)return u(a,
b,c)},showExpressInstall:function(a,b,d,g){o.w3&&e()&&c(a,b,d,g)},removeSWF:function(a){o.w3&&g(a)},createCSS:function(a,b,c,d){o.w3&&p(a,b,c,d)},addDomLoadEvent:j,addLoadEvent:i,getQueryParamValue:function(a){var b=q.location.search||q.location.hash;if(b){/\?/.test(b)&&(b=b.split("?")[1]);if(a==null)return s(b);for(var b=b.split("&"),c=0;c<b.length;c++)if(b[c].substring(0,b[c].indexOf("="))==a)return s(b[c].substring(b[c].indexOf("=")+1))}return""},expressInstallCallback:function(){if(G){var a=l(w);
if(a&&D){a.parentNode.replaceChild(D,a);if(H&&(n(H,!0),o.ie&&o.win))D.style.display="block";J&&J(L)}G=!1}}}}();
(function(){var a=FusionCharts(["private","FlashRenderer"]);if(a!==void 0){try{a.swfobject=window.swfobject,window.swfobject.createCSS("object.FusionCharts:focus, embed.FusionCharts:focus","outline: none")}catch(j){}a.core.options.requiredFlashPlayerVersion="8";a.core.options.flashInstallerUrl="http://get.adobe.com/flashplayer/";a.core.options.installRedirectMessage="You need Adobe Flash Player 8 (or above) to view the charts on this page. It is a free, lightweight and safe installation from Adobe Systems Incorporated.\n\nWould you like to go to Adobe's website and install Flash Player?";a.core.hasRequiredFlashVersion=
function(b){if(typeof b==="undefined")b=a.core.options.requiredFlashPlayerVersion;return window.swfobject?window.swfobject.hasFlashPlayerVersion(b):void 0};var i=!1,h=function(b,e){if(!(e&&e.source==="XmlHttpRequest")){var c=b.sender;if(c.ref&&typeof c.ref.dataInvokedOnSWF==="function"&&c.ref.dataInvokedOnSWF()&&typeof c.ref.getXML==="function")a.raiseWarning(c,"08300116","run","::DataHandler~__fusioncharts_vars","Data was set in UTF unsafe manner"),c.setChartData(window.unescape(b.sender.ref.getXML({escaped:!0})),
FusionChartsDataFormats.XML,!0),c.flashVars.dataXML=c.getChartData(FusionChartsDataFormats.XML),delete c.flashVars.dataURL;b.sender.removeEventListener("DataLoaded",h)}};window.__fusioncharts_dimension=function(){var b=/.*?\%\s*?$/g;return function(e){var c,d;return!((c=a.core(e))instanceof a.core&&c.ref&&(d=c.ref.parentNode))?{}:{width:d.offsetWidth*(b.test(c.width)?parseInt(c.width,10)/100:1),height:d.offsetHeight*(b.test(c.height)?parseInt(c.height,10)/100:1)}}}();window.__fusioncharts_vars=function(b,
e){var c=a.core.items[b];if(!(c instanceof a.core))return setTimeout(function(){var c;if(c=b!==void 0){var e=window.swfobject.getObjectById(b),f,g,i;c={};var h;if(!e&&typeof e.tagName!=="string")c=void 0;else{if((f=e.parentNode)&&f.tagName&&f.tagName.toLowerCase()==="object"&&f.parentNode)f=f.parentNode;if(f){c.renderAt=f;if(!(e.tagName!=="OBJECT"&&e.getAttribute&&(h=e.getAttribute("flashvars")||""))&&e.hasChildNodes&&e.hasChildNodes()){i=e.childNodes;f=0;for(e=i.length;f<e;f+=1)if(i[f].tagName===
"PARAM"&&(g=i[f].getAttribute("name"))&&g.toLowerCase()==="flashvars")h=i[f].getAttribute("value")||""}if(h&&typeof h.toString==="function"){h=h.split(/\=|&/g);c.flashVars={};f=0;for(e=h.length;f<e;f+=2)c.flashVars[h[f]]=h[f+1]}}else c=void 0}}c||a.raiseError(a.core,"25081621","run","::FlashRenderer","FusionCharts Flash object is accessing flashVars of non-existent object.")},0),!1;if(typeof e==="object"){if(c.ref&&typeof c.ref.dataInvokedOnSWF==="function"&&c.ref.dataInvokedOnSWF()){if(e.dataURL!==
void 0)c.addEventListener("DataLoaded",h);else if(e.dataXML!==void 0)e.dataXML=window.unescape(e.dataXML);c.__state.flashUpdatedFlashVars=!0}else delete e.dataURL,delete e.dataXML;a.extend(c.flashVars,e);return!0}if(c.__state.dataSetDuringConstruction&&c.flashVars.dataXML===void 0&&c.options.dataSource!==void 0&&typeof c.options.dataFormat==="string")c.flashVars.dataXML=c.options.dataSource;c.__state.flashInvokedFlashVarsRequest=!0;return c.flashVars};window.__fusioncharts_event=function(b,e){setTimeout(function(){a.raiseEvent(b.type,
e,a.core.items[b.sender])},0)};var f=function(b){b=b.sender;if(b.options.renderer==="flash"){if(b.width===void 0)b.width=a.renderer.policies.flashVars.chartWidth[1];if(b.height===void 0)b.height=a.renderer.policies.flashVars.chartHeight[1];if(b.flashVars.DOMId===void 0)b.flashVars.DOMId=b.id;a.extend(b.flashVars,{registerWithJS:"1",chartWidth:b.width,chartHeight:b.height,InvalidXMLText:"Invalid data."});if(Boolean(b.options.autoInstallRedirect)===!0&&!window.swfobject.hasFlashPlayerVersion(a.core.options.requiredFlashPlayerVersion.toString())&&
i===!1&&(i=!0,a.core.options.installRedirectMessage&&window.confirm(a.core.options.installRedirectMessage)))window.location.href=a.core.options.flashInstallerUrl;if(b.options.dataFormat===void 0&&b.options.dataSource===void 0)b.options.dataFormat=FusionChartsDataFormats.XMLURL,b.options.dataSource="Data.xml"}};a.renderer.register("flash",{dataFormat:"xml",init:function(){a.addEventListener("BeforeInitialize",f)},policies:{params:{scaleMode:["scaleMode","noScale"],scale:["scaleMode","noScale"],wMode:["wMode",
"opaque"],menu:["menu",void 0],bgColor:["bgColor",void 0],allowScriptAccess:["allowScriptAccess","always"],quality:["quality","best"],swLiveConnect:["swLiveConnect",void 0],base:["base",void 0],align:["align",void 0],salign:["sAlign",void 0]},flashVars:{lang:["lang","EN"],debugMode:["debugMode",void 0],scaleMode:["scaleMode","noScale"],animation:["animate",void 0]},options:{autoInstallRedirect:["autoInstallRedirect",!1],useLegacyXMLTransport:["_useLegacyXMLTransport",!1]}},render:function(b,e){Boolean(this.flashVars.animation)===
!0&&delete this.flashVars.animation;this.src||a.raiseError(this,"03102348","run","::FlashRenderer.render",'Could not find a valid "src" attribute. swfUrl or chart type missing.');var c={},d=this.flashVars.dataXML,f=this.flashVars.dataURL,h;a.extend(c,this.flashVars);if(this.flashVars.stallLoad===!0){if(this.options.dataFormat===FusionChartsDataFormats.XML)d=this.options.dataSource;if(this.options.dataFormat===FusionChartsDataFormats.XMLURL)f=this.options.dataSource}if(a.core.debugMode.enabled()&&
a.core.debugMode.syncStateWithCharts&&c.debugMode===void 0&&this.options.safeMode)c.debugMode="1";this.__state.lastRenderedSrc=this.src;c.dataXML=(typeof window.encodeURIComponent==="function"?window.encodeURIComponent(d):window.escape(d))||"";c.dataURL=a.isXSSSafe(f)?f||"":(typeof window.encodeURIComponent==="function"?window.encodeURIComponent(f):window.escape(f))||"";if(!window.swfobject||!window.swfobject.embedSWF||!window.swfobject.FusionChartsModified)window.swfobject=a.swfobject;i&&!a.core.options.installRedirectMessage&&
(h={silent:!0});window.swfobject&&window.swfobject.embedSWF?window.swfobject.embedSWF(this.src,b.id,this.width,this.height,a.core.options.requiredFlashPlayerVersion,void 0,c,this.params,this.attributes,e,h):a.raiseError(this,"1113061611","run","FlashRenderer~render",Error("Could not find swfobject library or embedSWF API"))},update:function(a){var e=this.ref,c=a.data;this.flashVars.dataXML=c;a.error===void 0?this.isActive()&&typeof e.setDataXML==="function"?this.src!==this.__state.lastRenderedSrc?
this.render():e.setDataXML(c,!1):(delete this.flashVars.dataURL,delete this.flashVars.animation):this.isActive()&&typeof e.showChartMessage==="function"?e.showChartMessage("InvalidXMLText"):(this.flashVars.dataXML="<Invalid"+a.format.toUpperCase()+">",delete this.flashVars.dataURL,delete this.flashVars.animation)},resize:function(){this.flashVars.chartWidth=this.width;this.flashVars.chartHeight=this.height;if(this.ref!==void 0)this.ref.width=this.width,this.ref.height=this.height,typeof this.ref.resize===
"function"&&this.ref.resize(this.ref.offsetWidth,this.ref.offsetHeight)},config:function(b){a.extend(this.flashVars,b)},dispose:function(){var a;window.swfobject.removeSWF(this.id);(a=this.ref)&&a.parentNode&&a.parentNode.removeChild(a)},protectedMethods:{flashVars:!0,params:!0,setDataXML:!0,setDataURL:!0,hasRendered:!0,getXML:!0,getDataAsCSV:!0,print:!0,exportChart:!0},events:{Loaded:function(a){a.sender.flashVars.animation="0"},DataLoadRequested:function(b,e){var c=b.sender,d=e.url,f=!1;if(e.dataFormat===
FusionChartsDataFormats.XML&&(window.location.protocol==="file:"&&Boolean(c.options.safeMode)||Boolean(c.options.useLegacyXMLTransport)))c.ref?c.ref.setDataURL?c.ref.setDataURL(d,!1):a.raiseError(this,"0109112330","run",">FlashRenderer^DataLoadRequested",Error("Unable to fetch URL due to security restriction on Flash Player. Update global security settings.")):c.flashVars.dataURL=d,b.stopPropagation(),f=!0,e.cancelDataLoadRequest(),c.addEventListener("DataLoaded",h);if(c.ref&&c.showChartMessage)delete c.flashVars.stallLoad,
c.options.showDataLoadingMessage&&c.ref.showChartMessage("XMLLoadingText");else if(!f)c.flashVars.stallLoad=!0},DataLoadRequestCancelled:function(a){a=a.sender;a.ref&&typeof a.showChartMessage==="function"&&a.ref.showChartMessage();delete a.flashVars.stallLoad},DataLoadError:function(a,e){var c=a.sender;c.ref&&typeof c.ref.showChartMessage==="function"&&e.source==="XmlHttpRequest"?c.ref.showChartMessage("LoadDataErrorText"):(delete c.flashVars.dataURL,c.flashVars.dataXML="<JSON parsing error>",delete c.flashVars.stallLoad)},
DataLoadRequestCompleted:function(a,e){e.source==="XmlHttpRequest"&&delete a.sender.flashVars.stallLoad}},prototype:{getSWFHTML:function(){var a=document.createElement("span"),e=document.createElement("span"),c="RnVzaW9uQ2hhcnRz"+(new Date).getTime();a.appendChild(e);e.setAttribute("id",c);a.style.display="none";document.getElementsByTagName("body")[0].appendChild(a);window.swfobject.embedSWF(this.src,c,this.width,this.height,"8.0.0",void 0,this.flashVars,this.params,this.attrs);e=a.innerHTML.replace(c,
this.id);window.swfobject.removeSWF(c);a.parentNode.removeChild(a);return e},setTransparent:function(a){typeof a!=="boolean"&&a!==null&&(a=!0);this.params.wMode=a===null?"window":a===!0?"transparent":"opaque"},registerObject:function(){},addVariable:function(){a.raiseWarning(this,"1012141919","run","FlashRenderer~addVariable()",'Use of deprecated "addVariable()". Replace with "configure()".');a.core.prototype.configure.apply(this,arguments)},setDataXML:function(b){a.raiseWarning(this,"11033001081",
"run","GenericRuntime~setDataXML()",'Use of deprecated "setDataXML()". Replace with "setXMLData()".');b===void 0||b===null||typeof b.toString!=="function"?a.raiseError(this,"25081627","param","~setDataXML",'Invalid data type for parameter "xml"'):this.ref===void 0||this.ref===null||typeof this.ref.setDataXML!=="function"?this.setChartData(b.toString(),FusionChartsDataFormats.XML):this.ref.setDataXML(b.toString())},setDataURL:function(b){a.raiseWarning(this,"11033001082","run","GenericRuntime~setDataURL()",
'Use of deprecated "setDataURL()". Replace with "setXMLUrl()".');b===void 0||b===null||typeof b.toString!=="function"?a.raiseError(this,"25081724","param","~setDataURL",'Invalid data type for parameter "url"'):this.ref===void 0||this.ref===null||typeof this.ref.setDataURL!=="function"?this.setChartData(b.toString(),FusionChartsDataFormats.XMLURL):this.ref.setDataURL(b.toString())}}});a.renderer.setDefault("flash")}})();
(function(){var a;a=FusionCharts(["private","modules.renderer.highcharts"]);if(a!==void 0){a.extend(a.core.options,{html5ScriptNameSuffix:".js",html5ScriptNamePrefix:"FusionCharts.HC.",jQuerySourceFileName:"jquery.min.js"});var j=window,i=a.core.options,h=function(){},f=a.hcLib={cmdQueue:[]},b=f.moduleCmdQueue={jquery:[],base:[],charts:[],powercharts:[],widgets:[],maps:[]},e=f.moduleDependencies={},c=f.moduleMeta={jquery:"jquery.min.js",base:"FusionCharts.HC.js",charts:"FusionCharts.HC.Charts.js",
powercharts:"FusionCharts.HC.PowerCharts.js",widgets:"FusionCharts.HC.Widgets.js",maps:"FusionCharts.HC.Maps.js"},d={},k=f.getDependentModuleName=function(a){var b=[],c,d;for(c in e)if((d=e[c][a])!==void 0)b[d]=c;return b};f.injectModuleDependency=function(a,c,d){var g=!1;c===void 0&&(c=a);e[a]||(e[a]={},b[a]||(b[a]=[],f.moduleMeta[a]=i.html5ScriptNamePrefix+c+i.html5ScriptNameSuffix),g=!0);e[a][c]=d||0;return g};var u=f.hasModule=function(b){var c,d;if(b instanceof Array){c=0;for(d=b.length;c<d;c+=
1)if(!Boolean(a.modules["modules.renderer.highcharts-"+b])||b==="jquery"&&!Boolean(window.jQuery))return!1;return!0}if(b==="jquery")return Boolean(window.jQuery);return Boolean(a.modules["modules.renderer.highcharts-"+b])};f.needsModule=function(a,b){return(f.moduleDependencies[a]&&f.moduleDependencies[a][b])!==void 0};var g=f.loadModule=function(b,g,e,f){b instanceof Array||(b=[b]);var i=b.length,k=0,h=function(){if(k>=i)g&&g();else{var l=b[k],j=c[l],r;k+=1;if(l)if(u(l)){h();return}else{if(d[l]){a.raiseError(f||
a.core,"1112201445A","run","JavaScriptRenderer~loadModule() ","required resources are absent or blocked from loading.");e&&e(l);return}}else e&&e(l);r=l==="jquery"?a.core.options.jQuerySourceFileName:a.core.options["html5"+a.capitalizeString(l)+"Src"];a.loadScript(r==void 0?j:r,{success:function(){u(l)?h():e&&e(l)},failure:e&&function(){e(l)}},void 0,!0)}};h()},l=f.executeWaitingCommands=function(a){for(var b;b=a.shift();)typeof b==="object"&&h[b.cmd].apply(b.obj,b.args)};f.cleanupWaitingCommands=
function(a){for(var c=a.chartType(),c=k(c),d,g=[],e;d=c.shift();){for(d=b[d]||[];e=d.shift();)typeof e==="object"&&e.obj!==a&&g.push(e);d.concat(g);g=[]}};var r=function(a){delete a.sender.jsVars._reflowData;a.sender.jsVars._reflowData={};delete a.sender.jsVars._reflowClean},m=function(){var a=function(){};a.prototype={LoadDataErrorText:"Error in loading data.",XMLLoadingText:"Retrieving data. Please wait",InvalidXMLText:"Invalid data.",ChartNoDataText:"No data to display.",ReadingDataText:"Reading data. Please wait",
ChartNotSupported:"Chart type not supported.",LoadingText:"Loading chart. Please wait",RenderChartErrorText:"Unable to render chart."};return a.prototype.constructor=a}();h.dataFormat="json";h.policies={jsVars:{},options:{showLoadingMessage:["showLoadingMessage",!0]}};h.ready=!1;h.init=function(){window.jQuery?u("base")?h.ready=!0:g("base",function(){h.ready=!0;l(f.cmdQueue)},void 0,a.core):g("jquery",function(){jQuery.noConflict();if(window.$===void 0)window.$=jQuery;h.init()},void 0,a.core)};h.render=
function(a){var b=a,c=this.jsVars,d=c.msgStore;if(b&&this.options.showLoadingMessage)b.innerHTML='<small style="display: inline-block; *zoom:1; *display:inline; width: 100%; font-family: Verdana; font-size: 10px; color: #666666; text-align: center; padding-top: '+(parseInt(b.style.height,10)/2-5)+'px">'+d.LoadingText+"</small>",b.style.backgroundColor=c.transparent?this.options.containerBackgroundColor||"transparent":"#ffffff";f.cmdQueue.push({cmd:"render",obj:this,args:arguments})};h.update=function(){f.cmdQueue.push({cmd:"update",
obj:this,args:arguments})};h.resize=function(){f.cmdQueue.push({cmd:"resize",obj:this,args:arguments})};h.dispose=function(){var a=f.cmdQueue,b,c;b=0;for(c=a.length;b<c;b+=1)a[b].obj===this&&(a.splice(b,1),c-=1,b-=1)};h.config=function(){f.cmdQueue.push({cmd:"config",obj:this,args:arguments})};h.load=function(){f.cmdQueue.push({cmd:"load",obj:this,args:arguments})};h.protectedMethods={};h.events={BeforeInitialize:function(a){var b=a.sender,a=b.jsVars,c=this.chartType();a.fcObj=b;a.msgStore=a.msgStore||
new m;a.cfgStore=a.cfgStore||{};a.previousDrawCount=-1;a.drawCount=0;a._reflowData={};if(!(a.userModules instanceof Array)&&(b=a.userModules,a.userModules=[],typeof b==="string"))a.userModules=a.userModules.concat(b.split(","));if(!f.chartAPI||!f.chartAPI[c])a.needsLoaderCall=!0},Initialized:function(a){var a=a.sender,b=a.jsVars;b.needsLoaderCall&&(delete b.needsLoaderCall,h.load.call(a))},BeforeDataUpdate:r,BeforeDispose:r,BeforeRender:function(a){var b=a.sender.jsVars;delete b.drLoadAttempted;delete b.waitingModule;
delete b.waitingModuleError;r.apply(this,arguments)},DataLoadRequested:function(a){var a=a.sender,b=a.jsVars;delete b.loadError;a.ref&&a.options.showDataLoadingMessage?b.hcObj&&!b.hasNativeMessage&&b.hcObj.showLoading?b.hcObj.showLoading(b.msgStore.XMLLoadingText):a.ref.showChartMessage?a.ref.showChartMessage("XMLLoadingText"):b.stallLoad=!0:b.stallLoad=!0},DataLoadRequestCompleted:function(a){delete a.sender.id.stallLoad},DataLoadError:function(a){var b=a.sender,c=b.jsVars;delete c.stallLoad;c.loadError=
!0;b.ref&&typeof b.ref.showChartMessage==="function"&&b.ref.showChartMessage("LoadDataErrorText");r.apply(this,arguments)}};h._call=function(a,b,c){a.apply(c||j,b||[])};a.extend(h.prototype,{getSWFHTML:function(){a.raiseWarning(this,"11090611381","run","JavaScriptRenderer~getSWFHTML()","getSWFHTML() is not supported for JavaScript charts.")},addVariable:function(){a.raiseWarning(this,"11090611381","run","JavaScriptRenderer~addVariable()",'Use of deprecated "addVariable()". Replace with "configure()".');
a.core.prototype.configure.apply(this,arguments)},getXML:function(){a.raiseWarning(this,"11171116291","run","JavaScriptRenderer~getXML()",'Use of deprecated "getXML()". Replace with "getXMLData()".');return this.getXMLData.apply(this,arguments)},setDataXML:function(){a.raiseWarning(this,"11171116292","run","JavaScriptRenderer~setDataXML()",'Use of deprecated "setDataXML()". Replace with "setXMLData()".');return this.setXMLData.apply(this,arguments)},setDataURL:function(){a.raiseWarning(this,"11171116293",
"run","JavaScriptRenderer~setDataURL()",'Use of deprecated "SetDataURL()". Replace with "setXMLUrl()".');return this.setXMLUrl.apply(this,arguments)},hasRendered:function(){return this.jsVars.hcObj&&this.jsVars.hcObj.hasRendered},setTransparent:function(a){var b;if(b=this.jsVars)typeof a!=="boolean"&&a!==null&&(a=!0),b.transparent=a===null?!1:a===!0?!0:!1}});a.extend(a.core,{_fallbackJSChartWhenNoFlash:function(){window.swfobject.hasFlashPlayerVersion(a.core.options.requiredFlashPlayerVersion)||a.renderer.setDefault("javascript")},
_enableJSChartsForSelectedBrowsers:function(b){b===void 0||b===null||a.renderer.setDefault(RegExp(b).test(navigator.userAgent)?"javascript":"flash")},_doNotLoadExternalScript:function(a){var b,g;for(b in a)g=b.toLowerCase(),c[g]&&(d[g]=Boolean(a[b]))},_preloadJSChartModule:function(){throw"NotImplemented()";}});a.renderer.register("javascript",h);window.swfobject&&window.swfobject.hasFlashPlayerVersion&&!window.swfobject.hasFlashPlayerVersion(a.core.options.requiredFlashPlayerVersion)&&(a.raiseWarning(a.core,
"1204111846","run","JSRenderer","Switched to JavaScript as default rendering due to absence of required Flash Player."),a.renderer.setDefault("javascript"))}})();(function(){var a=FusionCharts(["private","XMLDataHandler"]);if(a!==void 0){var j=function(a){return{data:a,error:void 0}};a.addDataHandler("XML",{encode:j,decode:j})}})();var JSON;JSON||(JSON={});
(function(){function a(a){return a<10?"0"+a:a}function j(a){f.lastIndex=0;return f.test(a)?'"'+a.replace(f,function(a){var b=c[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function i(a,c){var g,f,h,m,p=b,n,s=c[a];s&&typeof s==="object"&&typeof s.toJSON==="function"&&(s=s.toJSON(a));typeof d==="function"&&(s=d.call(c,a,s));switch(typeof s){case "string":return j(s);case "number":return isFinite(s)?String(s):"null";case "boolean":case "null":return String(s);
case "object":if(!s)return"null";b+=e;n=[];if(Object.prototype.toString.apply(s)==="[object Array]"){m=s.length;for(g=0;g<m;g+=1)n[g]=i(g,s)||"null";h=n.length===0?"[]":b?"[\n"+b+n.join(",\n"+b)+"\n"+p+"]":"["+n.join(",")+"]";b=p;return h}if(d&&typeof d==="object"){m=d.length;for(g=0;g<m;g+=1)typeof d[g]==="string"&&(f=d[g],(h=i(f,s))&&n.push(j(f)+(b?": ":":")+h))}else for(f in s)Object.prototype.hasOwnProperty.call(s,f)&&(h=i(f,s))&&n.push(j(f)+(b?": ":":")+h);h=n.length===0?"{}":b?"{\n"+b+n.join(",\n"+
b)+"\n"+p+"}":"{"+n.join(",")+"}";b=p;return h}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var h=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,b,e,c={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},d;if(typeof JSON.stringify!=="function")JSON.stringify=function(a,c,g){var f;e=b="";if(typeof g==="number")for(f=0;f<g;f+=1)e+=" ";else typeof g==="string"&&(e=g);if((d=c)&&typeof c!=="function"&&(typeof c!=="object"||typeof c.length!=="number"))throw Error("JSON.stringify");return i("",
{"":a})};if(typeof JSON.parse!=="function")JSON.parse=function(a,b){function c(a,d){var e,f,h=a[d];if(h&&typeof h==="object")for(e in h)Object.prototype.hasOwnProperty.call(h,e)&&(f=c(h,e),f!==void 0?h[e]=f:delete h[e]);return b.call(a,d,h)}var d,a=String(a);h.lastIndex=0;h.test(a)&&(a=a.replace(h,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+a+")"),typeof b==="function"?c({"":d},""):d;throw new SyntaxError("JSON.parse");}})();
(function(){var a=FusionCharts(["private","JSON_DataHandler"]);if(a!==void 0){window.JSON===void 0&&a.raiseError(this,"1113062012","run","JSONDataHandler",Error("Could not find library support for JSON parsing."));a.core.options.allowIESafeXMLParsing=["_allowIESafeXMLParsing",!0];var j=function(a){if(a===null||a===void 0||typeof a.toString!=="function")return"";return a=a.toString().replace(/&/g,"&amp;").replace(/\'/g,"&#39;").replace(/\"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},i=function(){var f=
{arr:{set:!0,trendlines:!0,vtrendlines:!0,line:{trendlines:!0,vtrendlines:!0},data:!0,dataset:!0,lineset:!0,categories:!0,category:!0,linkeddata:!0,application:!0,definition:!0,axis:!0,connectors:!0,connector:{connectors:!0},trendset:!0,row:{rows:!0},column:{columns:!0},label:{labels:!0},color:{colorrange:!0},dial:{dials:!0},pointer:{pointers:!0},point:{trendpoints:!0},process:{processes:!0},task:{tasks:!0},milestone:{milestones:!0},datacolumn:{datatable:!0},text:{datacolumn:!0},alert:{alerts:!0},
groups:{annotations:!0},items:{groups:!0},shapes:!0,shape:{shapes:!0},entitydef:!0,entity:{entitydef:!0}},tag:{chart:"linkedchart",map:"linkedmap",set:"data",vline:{chart:"data",dataset:"data",categories:"category",linkedchart:"data"},apply:{application:"application"},style:{definition:"definition"},marker:{application:"application",definition:"definition"},entity:{entitydef:"entitydef",data:"data"},shape:{shapes:"shapes"},connector:{connectors:{chart:"connector",linkedchart:"connector",map:"connectors",
linkedmap:"connectors"}},annotationgroup:{annotations:"groups"},annotation:{groups:"items"}},attr:{vline:{vline:"true"}},ins:{chart:!0,map:!0},dsv:{dataset:"data",categories:"category"},text:{target:"target",value:"value"},group:{styles:{definition:!0,application:!0},chart:{value:!0,target:!0},linkedchart:{value:!0,target:!0},markers:{definition:!0,application:!0,shapes:!0,connectors:!0},map:{entitydef:!0,data:!0},linkedmap:{entitydef:!0,data:!0}}},b={append:function(a,b,e,h){f.arr[e]&&(f.arr[e]===
!0||f.arr[e][h]===!0)?(b[e]instanceof Array||(b[e]=[]),b[e].push(a)):b[e]=a},child:function(c,d,e,h){var g,i,j,m,p,n;for(g=0;g<d.length;g+=1)switch(j=d[g],i=j.nodeName.toLowerCase(),j.nodeType){case 1:m=b.attr(j.attributes);n=f.ins[i];n===!0&&(p=m,m={},m[i]=p);n=f.attr[i];typeof n==="object"&&a.extend(m,n);if(n=f.tag[i])if(typeof n==="object"&&typeof n[e]==="object")for(p in p=void 0,n[e]){if(h[p]){i=n[e][p];break}}else typeof n==="object"&&typeof n[e]==="string"?i=n[e]:typeof n==="string"&&(i=n);
j.childNodes.length&&((n=f.group[e])&&n[i]?b.child(c,j.childNodes,i,h):b.child(m,j.childNodes,i,h));n=f.group[e];(!n||!n[i])&&b.append(m,c,i,e);break;case 3:if(n=f.text[e])i=n,m=j.data,b.append(m,c,i,e);n=f.dsv[e];if(typeof n==="string"&&h.chart&&parseInt(h.chart.compactdatamode,10))i=n,m=j.data,c[i]=c[i]?c[i]+m:m}},attr:function(a){var b,e={};if(!a||!a.length)return e;for(b=0;b<a.length;b+=1)e[a[b].nodeName.toLowerCase()]=a[b].value||a[b].nodeValue;return e}},e=function(c){var d={},f,i,g;if(typeof c!==
"object"&&typeof c.toString!=="function")return e.errorObject=new TypeError("xml2json.parse()"),d;for(var c=c.toString().replace(/<\!--[\s\S]*?--\>/g,"").replace(/<\?xml[\s\S]*?\?>/ig,"").replace(/&(?!([^;\n\r]+?;))/g,"&amp;$1"),c=c.replace(/^\s\s*/,""),h=/\s/,j=c.length;h.test(c.charAt(j-=1)););c=c.slice(0,j+1);if(!c)return d;try{if(window.DOMParser)f=(new window.DOMParser).parseFromString(c,"text/xml");else if(document.body&&a.core.options.allowIESafeXMLParsing){var m=document.createElement("xml");
m.innerHTML=c;document.body.appendChild(m);f=m.XMLDocument;document.body.removeChild(m)}else f=new ActiveXObject("Microsoft.XMLDOM"),f.async="false",f.loadXML(c);if(!f||!f.childNodes||!(f.childNodes.length===1&&(i=f.childNodes[0])&&i.nodeName&&(g=i.nodeName.toLowerCase())&&(g==="chart"||g==="map")))return e.errorObject=new TypeError("xml2json.parse()"),d}catch(p){e.errorObject=p}i?(i.attributes&&(d[g]=b.attr(i.attributes)),i.childNodes&&b.child(d,i.childNodes,g,d),delete e.errorObject):e.errorObject=
new TypeError("xml2json.parse()");return d};return function(a){delete e.errorObject;return{data:e(a),error:e.errorObject}}}(),h=function(){var a={items:{explode:{data:"set",groups:{annotations:"annotationgroup"},items:{groups:"annotation"}},text:{chart:{target:"target",value:"value"}},dsv:{dataset:{data:"dataset"},categories:{category:"categories"}},attr:{chart:{chart:"chart"},map:{map:"map"},linkedmap:{map:"map"},linkedchart:{chart:"chart"}},group:{styles:{definition:"style",application:"apply"},
map:{data:"entity",entitydef:"entity"},markers:{definition:"marker",application:"marker",shapes:"shape",connectors:"connector"}}},qualify:function(a,b,d){return typeof this.items[a][d]==="object"?this.items[a][d][b]:this.items[a][d]}},b=function(e,c,d,i){var h="",g="",l="",r="",m,p,n;c&&typeof c.toLowerCase==="function"&&(c=c.toLowerCase());if(d===void 0&&e[c])for(m in e[c])if(p=m.toLowerCase(),p==="compactdatamode")i.applyDSV=e[c][m]==1;if(e instanceof Array)for(m=0;m<e.length;m+=1)r+=typeof e[m]===
"string"?j(e[m]):b(e[m],c,d,i);else{for(m in e)p=m.toLowerCase(),e[m]instanceof Array&&(n=a.qualify("group",p,c))?g+="<"+p+">"+b(e[m],n,c,i)+"</"+p+">":typeof e[m]==="object"?(n=a.qualify("attr",p,c))?(l=b(e[m],n,c,i).replace(/\/\>/ig,""),c=p):g+=b(e[m],p,c,i):i.applyDSV&&(n=a.qualify("dsv",p,c))?g+=e[m]:(n=a.qualify("text",p,c))?g+="<"+n+">"+e[m]+"</"+n+">":p==="vline"&&Boolean(e[m])?c="vline":h+=" "+p+'="'+j(e[m]).toString().replace(/\"/ig,"&quot;")+'"';if(n=a.qualify("explode",d,c))c=n;r=(l!==
""?l:"<"+c)+h+(g!==""?">"+g+"</"+c+">":" />")}return r};return function(a){delete b.errorObject;if(a&&typeof a==="string")try{a=JSON.parse(a)}catch(c){b.errorObject=c}return{data:b(a,a&&a.map?"map":"chart",void 0,{}),error:b.errorObject}}}();a.addDataHandler("JSON",{encode:h,decode:i})}})();
(function(){var a=FusionCharts(["private","CSVDataHandler"]);if(a!==void 0){var j=function(a){this._data=[];this.columnCount=this.rowCount=0;this.configure(a)};j.prototype.set=function(a,h,f){var b;if(this.rowCount<=a){for(b=this.rowCount;b<=a;b+=1)this._data[b]=[];this.rowCount=a+1}if(this.columnCount<=h)this.columnCount=h+1;this._data[a][h]=f};j.prototype.configure=function(a){this.delimiter=this._decodePseudoCode(a.delimiter,",");this.qualifier=this._decodePseudoCode(a.qualifier,'"');this.eolCharacter=
this._decodePseudoCode(a.eolCharacter,"\r\n")};j.prototype._decodePseudoCode=function(a,h){if(a===void 0||a===null||!a.toString)return h;return a.replace("{tab}","\t").replace("{quot}",'"').replace("{apos}","'")};j.prototype.toString=function(){var a,h,f="";for(a=0;a<this.rowCount;a+=1)h=this.qualifier+this._data[a].join(this.qualifier+this.delimiter+this.qualifier)+this.qualifier,f+=h==='""'?this.eolCharacter:h+this.eolCharacter;this.rowCount>0&&(f=f.slice(0,f.length-2));return f};a.addDataHandler("CSV",
{encode:function(i,h){a.raiseError(h,"0604111215A","run","::CSVDataHandler.encode()","FusionCharts CSV data-handler only supports encoding of data.");throw"FeatureNotSupportedException()";},decode:function(i){var i=a.core.transcodeData(i,"xml","json")||{},h,f,b,e,c,d;if(typeof i.chart!=="object")i.chart={};h=new j({separator:i.chart.exportdataseparator,qualifier:i.chart.exportdataqualifier});if(i.dataset&&i.categories&&i.categories[0]&&i.categories[0].category)for(f=0;f<i.dataset.length;f+=1){h.set(0,
f+1,i.dataset[f].seriesname);e=b=0;for(c=i.categories[0].category.length;b<c;b+=1)i.categories[0].category[b].vline||(h.set(e+1,0,i.categories[0].category[b].label||i.categories[0].category[b].name),d=parseFloat(i.dataset[f]&&i.dataset[f].data&&i.dataset[f].data[e]?i.dataset[f].data[e].value:""),d=isNaN(d)?"":d,h.set(e+1,f+1,d),e+=1)}else if(i.data instanceof Array){h.set(0,1,i.chart&&i.chart.yaxisname?i.chart.yaxisname:"Value");c=i.data.length;for(f=0;f<c;f+=1)i.data[f].vline||(h.set(f+1,0,i.data[f].label||
i.data[f].name),d=parseFloat(i.data[f].value?i.data[f].value:""),d=isNaN(d)?"":d,h.set(f+1,1,d))}h.rowCount>0&&h.set(0,0,i.chart&&i.chart.xaxisname?i.chart.xaxisname:"Label");return{data:h.toString(),error:void 0}}});a.core.addEventListener("Loaded",function(a){a=a.sender;if(a.options.renderer==="javascript"&&!a.getDataAsCSV)a.getDataAsCSV=a.ref.getDataAsCSV=a.getCSVData})}})();
(function(){var a=FusionCharts(["private","DynamicChartAttributes"]);a!==void 0&&a.extend(a.core,{setChartAttribute:function(a,i){if(typeof a==="string"){var h=a,a={};a[h]=i}else if(a===null||typeof a!=="object")return;var h=0,f=this.getChartData(FusionChartsDataFormats.JSON),b,e=f.chart||f.graph||f.map||{};for(b in a)h+=1,a[b]===null?delete e[b.toLowerCase()]:e[b.toLowerCase()]=a[b];if(h>0){if(typeof e.animation==="undefined")e.animation="0";this.setChartData(f,FusionChartsDataFormats.JSON)}},getChartAttribute:function(j){var i=
(i=this.getChartData(FusionChartsDataFormats.JSON)).chart||i.graph||i.map;if(arguments.length===0||j===void 0||i===void 0)return i;var h,f;if(typeof j==="string")h=i[j.toString().toLowerCase()];else if(j instanceof Array){h={};for(f=0;f<j.length;f+=1)h[j[f]]=i[j[f].toString().toLowerCase()]}else a.raiseError(this,"25081429","param","~getChartAttribute()",'Unexpected value of "attribute"');return h}},!0)})();
(function(){var a=FusionCharts(["private","api.LinkManager"]);if(a!==void 0){a.policies.link=["link",void 0];var j=window.FusionChartsDOMInsertModes={REPLACE:"replace",APPEND:"append",PREPEND:"prepend"},i={},h=function(b,e){this.items={};this.root=b;this.parent=e;e instanceof a.core?this.level=this.parent.link.level+1:(i[b.id]=[{}],this.level=0)},f=function(a,e){return(a.options.containerElement===e.options.containerElement||a.options.containerElementId===e.options.containerElementId)&&a.options.insertMode===
j.REPLACE};h.prototype.configuration=function(){return i[this.root.id][this.level]||(i[this.root.id][this.level]={})};a.extend(a.core,{configureLink:function(b,e){var c;if(b instanceof Array){for(c=0;c<b.length;c+=1)typeof i[this.link.root.id][c]!=="object"&&(i[this.link.root.id][c]={}),a.extend(i[this.link.root.id][c],b[c]);i[this.link.root.id].splice(b.length)}else if(typeof b==="object"){if(typeof e!=="number")e=this.link.level;i[this.link.root.id][e]===void 0&&(i[this.link.root.id][e]={});a.extend(i[this.link.root.id][e],
b)}else a.raiseError(this,"25081731","param","~configureLink()","Unable to update link configuration from set parameters")}},!0);a.addEventListener("BeforeInitialize",function(b){if(b.sender.link instanceof h){if(b.sender.link.parent instanceof a.core)b.sender.link.parent.link.items[b.sender.id]=b.sender}else b.sender.link=new h(b.sender)});a.addEventListener("LinkedChartInvoked",function(b,e){var c=b.sender,d=c.clone({dataSource:e.data,dataFormat:e.linkType,link:new h(c.link.root,c)},!0),i=e.alias;
if(i){if(!d.swfSrcPath&&d.swfUrl)d.swfSrcPath=d.swfUrl.replace(/(.*?)?[^\/]*\.swf.*?/ig,"$1");d.type=i}c.args&&parseInt(c.args.animate,10)!==0&&delete d.animate;a.extend(d,c.link.configuration());a.raiseEvent("BeforeLinkedItemOpen",{level:c.link.level},c.link.root);a.core.items[d.id]instanceof a.core&&a.core.items[d.id].dispose();d=new a.core(d);if(!f(d,c)&&(!c.options.overlayButton||!c.options.overlayButton.message)){if(typeof c.options.overlayButton!=="object")c.options.overlayButton={};c.options.overlayButton.message=
"Close"}d.render();a.raiseEvent("LinkedItemOpened",{level:c.link.level,item:d},c.link.root)});a.addEventListener("OverlayButtonClick",function(b,e){if(e.id==="LinkManager"){var c=b.sender,d=c.link.level-1,h=c.link.parent,i=c.link.root;a.raiseEvent("BeforeLinkedItemClose",{level:d,item:c},i);setTimeout(function(){a.core.items[c.id]&&c.dispose();a.raiseEvent("LinkedItemClosed",{level:d},i)},0);!h.isActive()&&f(c,h)&&h.render()}});a.addEventListener("Loaded",function(b){if((b=b.sender)&&b.link!==void 0&&
b.link.root!==b&&b.link.parent instanceof a.core)if(b.ref&&typeof b.ref.drawOverlayButton==="function"){var e=a.extend({show:!0,id:"LinkManager"},b.link.parent.options.overlayButton);a.extend(e,b.link.parent.link.configuration().overlayButton||{});b.ref.drawOverlayButton(e)}else a.raiseWarning(b,"04091602","run","::LinkManager^Loaded","Unable to draw overlay button on object. -"+b.id)});a.addEventListener("BeforeDispose",function(b){var e=b.sender;e&&e.link instanceof h&&(e.link.parent instanceof
a.core&&delete e.link.parent.link.items[b.sender.id],delete i[e.id])});FusionChartsEvents.LinkedItemOpened="linkeditemopened";FusionChartsEvents.BeforeLinkedItemOpen="beforelinkeditemopen";FusionChartsEvents.LinkedItemClosed="linkeditemclosed";FusionChartsEvents.BeforeLinkedItemClose="beforelinkeditemclose"}})();
(function(){var a=FusionCharts(["private","PrintManager"]);if(a!==void 0){var j={enabled:!1,invokeCSS:!0,processPollInterval:2E3,message:"Chart is being prepared for print.",useExCanvas:!1,bypass:!1},i={getCanvasElementOf:function(b,c,d){if(b.__fusioncharts__canvascreated!==!0){var e=document.createElement("canvas"),f=a.core.items[b.id].attributes["class"];j.useExCanvas&&G_vmlCanvasManager&&G_vmlCanvasManager.initElement(e);e.setAttribute("class",f);e.__fusioncharts__reference=b.id;b.parentNode.insertBefore(e,
b.nextSibling);b.__fusioncharts__canvascreated=!0}b.nextSibling.setAttribute("width",c||b.offsetWidth||2);b.nextSibling.setAttribute("height",d||b.offsetHeight||2);return b.nextSibling},removeCanvasElementOf:function(a){var b=a.ref&&a.ref.parentNode?a.ref.parentNode:a.options.containerElement||window.getElementById(a.options.containerElementId);if(b){var c=b.getElementsByTagName("canvas"),d,e;e=0;for(d=c.length;e<d;e+=1)if(c[e].__fusioncharts__reference===a.id&&(b.removeChild(c[e]),a.ref))a.ref.__fusioncharts__canvascreated=
!1}},rle2rgba:function(a,b,c){typeof c!=="string"&&(c="FFFFFF");var a=a.split(/[;,_]/),d,e,f,h,i,j=0;for(e=0;e<a.length;e+=2){a[e]===""&&(a[e]=c);a[e]=("000000"+a[e]).substr(-6);f=parseInt("0x"+a[e].substring(0,2),16);h=parseInt("0x"+a[e].substring(2,4),16);i=parseInt("0x"+a[e].substring(4,6),16);for(d=0;d<a[e+1];d+=1)b[j]=f,b[j+1]=h,b[j+2]=i,b[j+3]=255,j+=4}return b},rle2array:function(a,b){typeof b!=="string"&&(b="FFFFFF");var c=a.split(";"),d,e;for(d in c){c[d]=c[d].split(/[_,]/);for(e=0;e<c[d].length;e+=
2)c[d][e]=c[d][e]===""?b:("000000"+c[d][e]).substr(-6)}return c},drawText:function(b,c,d,e){b=b.getContext("2d");d=d||2;e=e||2;b.clearRect(0,0,d,e);b.textBaseline="middle";b.textAlign="center";b.font="8pt verdana";b.fillStyle="#776666";typeof b.fillText==="function"?b.fillText(c,d/2,e/2):typeof b.mozDrawText==="function"?(b.translate(d/2,e/2),b.mozDrawText(c)):a.raiseWarning(a.core,"25081803","run","::PrintManager>lib.drawText","Canvas text drawing is not supported in browser");return!0},appendCSS:function(a){var b=
document.createElement("style");b.setAttribute("type","text/css");typeof b.styleSheet==="undefined"?b.appendChild(document.createTextNode(a)):b.styleSheet.cssText=a;return document.getElementsByTagName("head")[0].appendChild(b)}};i.drawRLE=function(a,b,c,d,e){c=c||2;d=d||2;a.setAttribute("width",c);a.setAttribute("height",d);a=a.getContext("2d");if(typeof a.putImageData==="function"&&typeof a.createImageData==="function")c=a.createImageData(c,d),i.rle2rgba(b,c.data,e),a.putImageData(c,0,0);else for(e in c=
i.rle2array(b,e),d=e=b=0,c)for(d=b=0;d<c[e].length;d+=2)a.fillStyle="#"+c[e][d],a.fillRect(b,e,c[e][d+1],1),b+=parseInt(c[e][d+1],10);return!0};var h={styles:{print:"canvas.FusionCharts{display:none;}@media print{object.FusionCharts{display:none;}canvas.FusionCharts{display:block;}}",error:"canvas.FusionCharts{display:none;}",normal:""},cssNode:void 0},f={},b={},e=0,c;h.invoke=function(a){typeof this.styles[a]!=="undefined"&&(a=this.styles[a]);if(typeof a!=="undefined")this.cssNode!==void 0&&this.cssNode.parentNode!==
void 0&&this.cssNode.parentNode.removeChild(this.cssNode),h.cssNode=i.appendCSS(a)};var d=function(b){var d=b.sender.ref,k,m;if(d===void 0||typeof d.prepareImageDataStream!=="function"||d.prepareImageDataStream()===!1)c(b.sender);else{f[b.sender.id]||(f[b.sender.id]=d,e+=1,e===1&&a.raiseEvent("PrintReadyStateChange",{ready:!1,bypass:j.bypass},b.sender));try{k=d.offsetWidth,m=d.offsetHeight,i.drawText(i.getCanvasElementOf(d,k,m),j.message,k,m)}catch(p){h.invoke("error"),a.raiseError(b.sender,"25081807",
"run","::PrintManager>onDrawComplete","There was an error while showing message to user via canvas.")}}},k=function(b,c){try{i.drawRLE(i.getCanvasElementOf(b.sender.ref,c.width,c.height),c.stream,c.width,c.height,c.bgColor)===!0&&f[b.sender.id]&&(delete f[b.sender.id],e-=1,e===0&&a.raiseEvent("PrintReadyStateChange",{ready:!0,bypass:j.bypass},b.sender))}catch(d){h.invoke("error"),a.raiseError(b.sender,"25081810","run","::PrintManager>onImageStreamReady","There was an error while drawing canvas.")}},
u=function(a){i.removeCanvasElementOf(a.sender)};c=function(c){var e;if(c instanceof a.core)b[c.id]=c;else for(e in b)d({sender:b[e]},{}),delete b[e]};a.extend(a.core,{printManager:{configure:function(b){a.extend(j,b||{})},isReady:function(){if(j.bypass)return!0;if(e>0||!j.enabled)return!1;var b,c;for(b in a.core.items)if((c=a.core.items[b].ref)!==void 0&&c.hasRendered&&c.hasRendered()===!1)return!1;return!0},enabled:function(b){if(b===void 0)return j.enabled;if(a.renderer.currentRendererName()!==
"flash"||typeof document.createElement("canvas").getContext!=="function")return j.bypass=!0,a.raiseEvent("PrintReadyStateChange",{ready:!0,bypass:j.bypass}),a.raiseWarning(a.core,"25081816","run",".printManager.enabled","printManager is not compatible with your browser"),j.enabled;j.bypass=!1;var e=b?"addEventListener":"removeEventListener";a.core[e]("ImageStreamReady",k);a.core[e]("DrawComplete",d);a.core[e]("BeforeDispose",u);if(b===!0){var f;j.invokeCSS===!0&&h.invoke("print");for(f in a.core.items)c(a.core.items[f]),
c()}else{var m;h.invoke("error");for(m in a.core.items)i.removeCanvasElementOf(a.core.items[m]);j.bypass||a.raiseEvent("PrintReadyStateChange",{ready:!1,bypass:j.bypass});h.invoke("normal")}return j.enabled=b},managedPrint:function(b){j.bypass?window.print():a.core.printManager.isReady()?typeof b==="object"&&b.ready!==!0||(a.removeEventListener("PrintReadyStateChange",a.core.printManager.managedPrint),window.print()):a.core.printManager.enabled(!0)!==!0?window.print():a.addEventListener("PrintReadyStateChange",
a.core.printManager.managedPrint)}}},!1);FusionChartsEvents.PrintReadyStateChange="printreadystatechange"}})();
