Nm_erro = {
  "lang_jscr_dcml" : "Desimaalit",
  "lang_jscr_decm" : "Kymmenesosa sekuntia",
  "lang_jscr_hour" : "Tunti",
  "lang_jscr_iday" : "Päivä",
  "lang_jscr_intg" : "Kokonaisluvut ja",
  "lang_jscr_ivcr" : "Kelpaamaton luottokortin numero",
  "lang_jscr_ivdt" : "Kelpaamaton tieto:",
  "lang_jscr_ivem" : "Kelpaamaton sähköpostiosoite:",
  "lang_jscr_ivnb" : "Kelpaamaton kokonaisluku",
  "lang_jscr_ivtm" : "Kelpaamaton aika:",
  "lang_jscr_ivv2" : "Kelpaamaton tieto:",
  "lang_jscr_ivvl" : "Kelpaamaton desimaali",
  "lang_jscr_maxm" : "Max",
  "lang_jscr_maxm_date" : "Max päivämäärä",
  "lang_jscr_minm" : "Min",
  "lang_jscr_minm_date" : "Min päivämäärä",
  "lang_jscr_mint" : "Minuutit",
  "lang_jscr_mnth" : "Kuukausi",
  "lang_jscr_msfr" : "Lomakkeella täytyy olla nimi",
  "lang_jscr_mslg" : "kirjautuminen puuttuu;",
  "lang_jscr_msob" : "Lomakkeen aiheella täytyy olla nimi",
  "lang_jscr_mxdg" : "Numeroiden määrä ylittyi",
  "lang_jscr_mxvl" : "Max pituus ylittyi",
  "lang_jscr_nnum" : "Kenttä on numeerinen",
  "lang_jscr_nvlf" : "Negatiivinen merkki tulee olla arvon vasemmalla puolella",
  "lang_jscr_reqr" : "Pakollinen kenttä",
  "lang_jscr_secd" : "Sekuntit",
  "lang_jscr_wfix" : "- Haluatko korjata?"
}
