
  <div class="page-content row">
    <!-- Page header -->
    <div class="page-header">
      <div class="page-title">
        <h3> Help <small> Developer Guide </small></h3>
      </div>

      <ul class="breadcrumb">
        <li><a href="{{ URL::to('config/dashboard') }}">Home</a></li>
        <li><a href="{{ URL::to('config/help') }}">Help</a></li>
        <li class="active"> Developer </li>
      </ul>
	</div>  
 <div class="page-content-wrapper m-t">  

	@include('admin.config.manual.developersidebar')
	<div class="col-md-8" style="margin-bottom:50px;">
	
		<h2 > Controller Structure </h2>
		<p> Every controller generated by code builder will have same structure and code</p>
		<h6> Controller code </h6> 
<pre class="prettyprint linenums lang-php ">
class ModuleController extends BaseController {
	protected $layout = "layouts.main";
	protected $data = array();	
	public $module = 'pages';
	static $per_page	= '10';
	public function __construct() {
		parent::__construct();
	}

	public function getIndex()
	{
		/* Handle table grid , sort order , 
			pagination and search proccess */ 
	}

	function getAdd( $id = null)
	{
		/* Handle form add or edit */ 
	}

	function getShow( $id = null)
	{
		/* Handle view detail*/ 
	}

	function postSave( $id =0)
	{
		/* Handle post form from add or edit */ 
	}

	public function postDestroy()
	{
		/* Handle multiple delete  */ 

	}							
}
</pre>
					
</div>
</div>
</div>

