
  <div class="page-content row">
    <!-- Page header -->
    <div class="page-header">
      <div class="page-title">
        <h3> Help <small> Developer Guide </small></h3>
      </div>

      <ul class="breadcrumb">
        <li><a href="{{ URL::to('config/dashboard') }}">Home</a></li>
        <li><a href="{{ URL::to('config/help') }}">Help</a></li>
        <li class="active"> Developer </li>
      </ul>
	</div> 
 <div class="page-content-wrapper m-t">  

	@include('admin.config.manual.developersidebar')
	<div class="col-md-8" style="margin-bottom:50px;">
	
		<h2 > Model Structure </h2>

			<p>Every Model generated by code builder will have same structure and code </p>
			<h6> Model code </h6>
<pre class="prettyprint lang-php">
class Module extends BaseModel  {
	
	protected $table = 'table';
	protected $primaryKey = 'key';

	public function __construct() {
		parent::__construct();
		
	}

	public static function querySelect(  ){
		
		
		return "  SELECT table.* FROM table  ";
	}
	public static function queryWhere(  ){
		
		return " WHERE table.key IS NOT NULL   ";
	}
	
	public static function queryGroup(){
		return "  ";
	}
	

}

</pre>
					
</div>
</div>
</div>

